spring:
 application:
   name: public-point
 data:
   cassandra:
     contact-points: 127.0.0.1
     keyspace-name: ocds
     port: 9042
     username: cassandra
     password: cassandra

ocds:
 path: https://point.eprocurement.systems/
 version: 1.1
 license: http://opendefinition.org/licenses/
 publicationPolicy: http://opendefinition.org/licenses/
 extensions:
   https://raw.githubusercontent.com/open-contracting/ocds_bid_extension/v1.1.1/extension.json,
   https://raw.githubusercontent.com/open-contracting/ocds_enquiry_extension$/v1.1.1/extension.json
 publisherName: publisher-name
 publisherScheme: publisher-scheme
 publisherUid: publisher-uid
 publisherUri: publisher-uri