server:
  port: 8080

spring:
  application:
    name: public-point
  data:
    cassandra:
      contact-points: 10.0.20.104,10.0.20.105,10.0.20.106
      keyspace-name: ocds
      username: caclient
      password: 6AH7vbrkMWnfK

eureka:
  client:
    enabled: false

ocds:
  path: http://public.eprocurement.systems/
  version: 1.1
  license: http://opendefinition.org/licenses/
  publicationPolicy: http://opendefinition.org/licenses/
  extensions:
    https://raw.githubusercontent.com/open-contracting/ocds_bid_extension/v1.1.1/extension.json,
    https://raw.githubusercontent.com/open-contracting/ocds_enquiry_extension$/v1.1.1/extension.json
  publisherName: M-Tender
  publisherUri: https://www.mtender.gov.md
  limit: 300

health:
  config:
    enabled: false

management:
  health:
    #    diskspace:
    #      enabled: true
    db:
      enabled: true
    #    refresh:
    #      enabled: false
    defaults:
      enabled: false

  endpoint:
    health:
      show-details: always

  #    loggers:
  #      enabled: true

  endpoints:
    web:
      exposure:
        include: "health,prometheus"

#    jmx:
#      domain: com.procurement
#      exposure:
#        exclude: "*"

#  metrics:
#    distribution:
#      percentiles-histogram:
#        http:
#          server:
#            requests: true
#      sla:
#        http:
#          server:
#            requests: 1ms,5ms
#  server:
#    port: 9999
#  info:
#    git:
#      mode: full