server:
  port: 8080

spring:
  application:
    name: public-point
  data:
    cassandra:
      contact-points: localhost
      keyspace-name: ocds

  cache:
    jcache:
      config: classpath:ehcache.xml
eureka:
  client:
    enabled: false

ocds:
  path: http://public.example.com/
  limit: 300

health:
  config:
    enabled: false

management:
  health:
    #    diskspace:
    #      enabled: true
    db:
      enabled: true
    #    refresh:
    #      enabled: false
    defaults:
      enabled: false

  endpoint:
    health:
      show-details: always

  #    loggers:
  #      enabled: true

  endpoints:
    web:
      exposure:
        include: "health,prometheus"

#    jmx:
#      domain: com.procurement
#      exposure:
#        exclude: "*"

#  metrics:
#    distribution:
#      percentiles-histogram:
#        http:
#          server:
#            requests: true
#      sla:
#        http:
#          server:
#            requests: 1ms,5ms
#  server:
#    port: 9999
#  info:
#    git:
#      mode: full